### ISSUE TITLE
Add .gitignore for python

### ISSUE THREAD

**Issue by LinguList** [martino-vic/loanpy#14]
In `tests` you have shared you __pycache__

**Comment by martino-vic** [comment]
Ah, well spotted! **/\_\_pycache\_\_/ in the [.gitignore](
https://github.com/martino-vic/loanpy/blob/2.0-beta/.gitignore) should prevent that from now on

["A leading "\*\*" followed by a slash means match in all directories. For example, "**/foo" matches file or directory "foo" anywhere"](https://git-scm.com/docs/gitignore)
