### ISSUE TITLE
LingPy's align method can be used more efficiently

### ISSUE THREAD

**Issue by LinguList** [martino-vic/loanpy#16]
https://github.com/martino-vic/loanpy/blob/b073e367c31ef87c3b3e694b6f2c2adfa7abd2fa/qfysc.py#L405

What you do is to convert the alignment of two strings to a string, then pull out the info. But Pairwise works like this:

```python
pw = Pairwise(["a", "b", "c"], ["b", "c", "a"]) # if you have segmented data, no need to take care of merging
pw.align(distance=True)
almA, almB, dist = pw.alignments[0]
```

You see? The alignment is accessible via the `alignments` attribute. Since Pairwise handles more than just one pair, this is in position 0, if only one pair has been passed.

**Comment by martino-vic** [comment]
Cool! Replaced the line with `leftright = [pw.alignments[0], pw.alignments[1]]` and it didn't even break the tests :) Closing this issue now
