### ISSUE TITLE
Where is the `setup.py`

### ISSUE THREAD

**Issue by LinguList** [martino-vic/loanpy#17]
I was curious: how do you deploy data on pypi? I could not find the `setup.py` script, is it in another repository?

**Comment by martino-vic** [comment]
I'm keeping a separate folder on my computer for the upload to PyPi, wasn't aware this would be useful for sharing. I have Included the [setup.py](https://github.com/martino-vic/loanpy/blob/2.0-beta/setup.py) file now in this repo

**Comment by LinguList** [comment]
Normal structure is to put the source code into `src/loanpy/`. If you check the structure we have in `lingpy`, you can just copy that. Or in `pysem`. It is recommendable, I think, as it is more transparent. Every (?) Python package maker will first look for a `src` directory in your main repository.

**Comment by martino-vic** [comment]
Now the structure should be fine I think

**Comment by LinguList** [comment]
Yes, you can even move tests to the base level.

**Comment by martino-vic** [comment]
Yeah, I was thinking about this. Have implemented it now.

**Comment by LinguList** [comment]
Nice.
