### ISSUE TITLE
bugfix (?) lingpy's prosodic_string func

### ISSUE THREAD

**Issue by martino-vic** [martino-vic/loanpy#44]
Vowels with tie bars, i.e. diphthongs, are transcribed as one vowel, i.e. prosodic_string("a͡e", _output="cv") == "V". Might be that this is generally the preferred way to transcribe this. For my own use case, this kinda seems to have fixed the issue for now:

```
        lexseg = []  # replace tie bars in vowels with space
        for i in ipa_in:
            if chr(865) in i and prosodic_string(  # tie bar
            i.split(" "), _output='cv') == "V":
                i = i.split(chr(865))
                lexseg += i
            else:
                lexseg.append(i)
```

**Comment by martino-vic** [comment]
Seems like diphthongs can't be handled by adapt() and have to always be inputted as separate vowels

**Comment by LinguList** [comment]
If you check how many diphthongs there are on CLTS, and how many possibilities there are, you will see that this is the best solution to leave this to the user to do it, rather than to leave it to a machine to guess it. At least for now.
